version: '3.4'

services:
  image: ui
    build:
      context: .
      dockerfile: src/Ui/Dockerfile
    depends_on:
      - db
      - rabbitmq
    networks:
      - common_network

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1q2w3e4r@#$
      - MSSQL_PID=Express
    restart: unless-stopped
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - common_network

  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management UI port
    networks:
      - common_network

volumes:
  db-data:

networks:
  common_network:
